server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  basic:
    enabled: false
  oauth2:
    client:
      client-id: client1
      client-secret: test1
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token
      
logging:
  level:
    org.springframework.security: DEBUG